def cipher(text):
    letter=''
    l=len(text)
    value=0
    i=0
    while(i<l):
        letter=text[i]
        if(letter==' '):
            value=13
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='A'):
            value=21
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='B'):
            value=15
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='C'):
            value=10
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='D'):
            value=6
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='E'):
            value=3
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='F'):
            value=1
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='G'):
            value=2
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='H'):
            value=4
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='I'):
            value=7
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='J'):
            value=11
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='K'):
            value=16
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='L'):
            value=22
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='M'):
            value=23
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='N'):
            value=24
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='O'):
            value=25
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='P'):
            value=26
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='Q'):
            value=0
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='R'):
            value=20
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='S'):
            value=14
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='T'):
            value=9
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='U'):
            value=5
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='V'):
            value=8
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='W'):
            value=12
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='X'):
            value=17
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='Y'):
            value=18
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='Z'):
            value=19
            if(i%5==0):
                value=value+8
                print('{0:2}'.format(value))
            elif(i%5==1):
                value=value+5
                print('{0:2}'.format(value))
            elif(i%5==2):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==3):
                value=value+12
                print('{0:2}'.format(value))
            elif(i%5==4):
                value=value+15
                print('{0:2}'.format(value))
            else:
                print('Not valid.')
        elif(letter=='.'):
            print(letter)
        else:
            print('Not valid')
        i=i+1
def decipher():
    n=0
    count=0
    message=""
    n=eval(input('Please enter one number at a time(ignore periods), enter 100 to indicate that you are done: '))
    while(n<100):
        if(count%5==0):
            n=n-8
        elif(count%5==1):
            n=n-5
        elif(count%5==2):
            n=n-12
        elif(count%5==3):
            n=n-12
        elif(count%5==4):
            n=n-15
        count=count+1
        if(n==0):
            message=message+"Q"
        elif(n==1):
            message=message+'F'
        elif(n==2):
            message=message+'G'
        elif(n==3):
            message=message+'E'
        elif(n==4):
            message=message+'H'
        elif(n==5):
            message=message+'U'
        elif(n==6):
            message=message+'D'
        elif(n==7):
            message=message+'I'
        elif(n==8):
            message=message+'V'
        elif(n==9):
            message=message+'T'
        elif(n==10):
            message=message+'C'
        elif(n==11):
            message=message+'J'
        elif(n==12):
            message=message+'W'
        elif(n==13):
            message=message+' '
        elif(n==14):
            message=message+'S'
        elif(n==15):
            message=message+'B'
        elif(n==16):
            message=message+'K'
        elif(n==17):
            message=message+'X'
        elif(n==18):
            message=message+'Y'
        elif(n==19):
            message=message+'Z'
        elif(n==20):
            message=message+'R'
        elif(n==21):
            message=message+'A'
        elif(n==22):
            message=message+'L'
        elif(n==23):
            message=message+'W'
        elif(n==24):
            message=message+'N'
        elif(n==25):
            message=message+'O'
        elif(n==26):
            message=message+'P'
        n=eval(input('Enter your next number: '))
    print(message)
def main():
    print('Enter 1 for cipher.')
    choice=eval(input('Enter 2 for decipher: '))
    if(choice==1):
        text=input('Enter all text in caps: ')
        cipher(text)
    else:
        decipher()
main()
